packages:
  - 'apps/*'
  - 'packages/*'
  - 'supabase'

allowBuilds:
  core-js: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - esbuild
